CREATE DATABASE chatwoot_db OWNER postgresadmin;
CREATE DATABASE odoo_db OWNER postgresadmin;

\connect chatwoot_db
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS vector;

\connect odoo_db
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
